name: Release CI

on:
  release:
    types: [released]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decode google-services.json
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: echo $FIREBASE_CONFIG > app/google-services.json
    - name: Decode keystore
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASS }}" --batch release.keystore.asc > release.keystore.jks
        echo "${{ secrets.RELEASE_KEYSTORE_PROPS }}" > keystore.properties.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASS }}" --batch keystore.properties.asc > keystore.properties
    - name: Run Android Linter
      run: ./gradlew :app:lint
    - name: Run SonarCloud scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube
    - name: Assemble Release APK
      run: ./gradlew :app:assembleRelease
    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: hu.polidor.webapprunner
        releaseFile: app/build/outputs/apk/release/app-release.apk
        whatsNewDirectory: distribution/whatsnew
        mappingFile: app/build/outputs/mapping/release/mapping.txt